FROM mcr.microsoft.com/devcontainers/java:1-11-bookworm

RUN wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
RUN tar -xvf apache-maven-3.9.9-bin.tar.gz && rm apache-maven-3.9.9-bin.tar.gz
RUN mv apache-maven-3.9.9 /opt/
ENV PATH=/opt/apache-maven-3.9.9/bin:$PATH

# Spark Installation
WORKDIR /opt/spark
RUN curl -O https://archive.apache.org/dist/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz && \
    tar -xvf spark-3.2.0-bin-hadoop3.2.tgz && \
    chmod -R 777 /opt/spark

# Hadoop Installation
WORKDIR /opt/hadoop
RUN curl -O https://dlcdn.apache.org/hadoop/common/hadoop-3.4.0/hadoop-3.4.0-aarch64.tar.gz && \
    tar -xvf hadoop-3.4.0-aarch64.tar.gz && \
    chmod -R 777 /opt/hadoop

# Coursier Installation
WORKDIR /opt/coursier
RUN curl -fL https://github.com/VirtusLab/coursier-m1/releases/latest/download/cs-aarch64-pc-linux.gz --output cs.gz && \
    cat cs.gz | gzip -d > cs && chmod +x cs && mv cs /usr/local/bin/

# Set Environment Variables
ENV SPARK_HOME=/opt/spark/spark-3.2.0-bin-hadoop3.2
ENV HADOOP_HOME=/opt/hadoop/hadoop-3.4.0
ENV PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

# Wayang environment variables
ENV WAYANG_HOME=/workspaces/wayang/wayang-0.7.1
ENV PATH=$PATH:$WAYANG_HOME/bin

# Copy the Wayang project from the host machine into the container
WORKDIR /opt/wayang
COPY incubator-wayang /opt/wayang

# Expose necessary ports (adjust as needed)
EXPOSE 8080 7077 4040

# Default command
CMD ["bash"]
